seleniumhub:
  image: selenium/hub
  ports:
    - 4444:4444

firefoxnode1:
  image: selenium/node-firefox
  ports:
    - 5900
  links:
    - seleniumhub:hub

chromenode1:
  image: selenium/node-chrome
  ports:
    - 5900
  links:
    - seleniumhub:hub

chromenode2:
  image: selenium/node-chrome
  ports:
    - 5900
  links:
    - seleniumhub:hub

chromenode3:
  image: selenium/node-chrome
  ports:
    - 5900
  links:
    - seleniumhub:hub

chromenode4:
  image: selenium/node-chrome
  ports:
    - 5900
  links:
    - seleniumhub:hub

chromenode5:
  image: selenium/node-chrome
  ports:
    - 5900
  links:
    - seleniumhub:hub
